--Q1. What is the total revenue generated by male vs. female customers?
--Q2. Which customers used a discount but still spent more than the average purchase amount?
--Q3. Which are the top 5 products with the highest average review rating?
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
--Q8. What are the top 3 most purchased products within each category?
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
--Q10. What is the revenue contribution of each age group?

Select * from customer limit 5;
--Q1. What is the total revenue generated by male vs. female customers?
Select gender,sum(purchase_amount) as total_revenue
from customer
group by gender
order by total_revenue desc;
Select * from customer limit 5;
--Q2. Which customers used a discount but still spent more than the average purchase amount?
Select customer_id,purchase_amount
from customer
where discount_applied='Yes' and
purchase_amount> (Select avg(purchase_amount) from customer);

Select * from customer limit 5;

--Q3. Which are the top 5 products with the highest average review rating?

Select item_purchased,
ROUND(AVG(review_rating::NUMERIC),2) as review_avg
from customer
group by item_purchased
order by review_avg desc
limit 5;

 	
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

Select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Express','Standard')
group by shipping_type;


--Select 
--AVG(CASE when shipping_type='Express' then purchase_amount end)-
--AVG(CASE when shipping_type='Standard'then purchase_amount end) as avg_diff
--from customer;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

Select subscription_status,
Count(customer_id) as total_customers,
ROUND(avg(purchase_amount),2) as avg_spend,
ROUND(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Select item_purchased,
ROUND(100 * SUM(CASE when discount_applied='Yes' then 1 else 0 END)/COUNT(*),2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;

Select * from customer limit 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
Select Max(previous_purchases),min(previous_purchases)
from customer;

--Select Customer_id,
--CASE WHEN previous_purchases between 1 and 15 then 'New'
--WHEN previous_purchases between 16 and 30 then 'Returning'
--else 'Loyal'
--end as customer_segment
--from customer;

with customer_type as (
Select customer_id,previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
	ELSE 'Loyal'
	END as customer_segment 
from customer
)
Select customer_segment,count(*) as Number_of_customer
from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select 
category,
item_purchased,
count(customer_id) as most_purchased,
ROW_NUMBER()over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased

)
Select * from item_counts where item_rank<=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;

--Q10. What is the revenue contribution of each age group?
Select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;